openapi: 3.0.2
info:
  title: LightWebService Authentication Server
  version: 1.0.0
servers:
  - url: https://localhost
    description: LWS Individual Web Server
tags:
  - name: Account
    description: Account(Register, Edit, Dropout) Related APIs
paths:
  /api/account:
    get:
      security:
        - AccessTokenSecurity: []
      tags:
        - Account
      summary: Get Account Information, Except for password
      description: This API will get account information, such as email address and nickname.
      responses:
        200:
          description: When successfully got account information.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountResponse"
        401:
          description: When API Request is not authorized.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: Somehow account information is not found.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
    post:
      tags:
        - Account
      summary: Register Account
      description: This API will add new account entity and send event message to Kubernetes Server(for creating user-default namespaces)
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterRequest"
      responses:
        200:
          description: When successfully registered account
components:
  schemas:
    $ref: "./auth_schemas.yaml"
  securitySchemes:
    $ref: "../common/security.yaml"
